name: x86build
on:
  push:
    branches:
      - webview2-wine96
jobs:
  auto_build:
    name: Auto Build x86/Linux images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: "webview2"
      - name: build docker
        env:
          DOCKERUSR: ${{ secrets.DOCKERUSR }}
        run: |
          echo "Build Docker"
          wget https://github.com/poynt2005/docker-wine-dotnet/releases/download/0.0/webview2.exe -O webview2.exe
          docker build -t ${DOCKERUSR}/docker-wine-dotnet:webview2 -f Dockerfile .
      - name: push to docker hub
        env:
          DOCKERUSR: ${{ secrets.DOCKERUSR }}
          DOCKERPASS: ${{ secrets.DOCKERPASS }}
        run: |
          echo "Docker Hub login"
          docker login --username ${DOCKERUSR} --password ${DOCKERPASS}
          echo "Push image"
          docker push ${DOCKERUSR}/docker-wine-dotnet:webview2
