name: x86build
on:
  push:
    branches:
      - dotnet48
jobs:
  auto_build:
    name: Auto Build x86/Linux images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@dotnet48
      - name: build docker
        env:
          DOCKERUSR: ${{ secrets.DOCKERUSR }}
        run: |
          echo "Build Docker"
          docker build -t ${DOCKERUSR}/docker-wine-dotnet:dotnet48 -f dockerfile .
      - name: push to docker hub
        env:
          DOCKERUSR: ${{ secrets.DOCKERUSR }}
          DOCKERPASS: ${{ secrets.DOCKERPASS }}
        run: |
          echo "Docker Hub login"
          docker login --username ${DOCKERUSR} --password ${DOCKERPASS}
          echo "Push image"
          docker push ${DOCKERUSR}/docker-wine-dotnet:dotnet48